version: "3.8"
services:
  postgres:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aryahmph
      POSTGRES_PASSWORD: aryahmph
      POSTGRES_DB: synapsis_challange
  web:
    build: .
    ports:
      - "4001:4001"
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres