### Create user
POST http://localhost:4001/api/v1/users
Content-Type: application/json

{
  "email": "aryayun90@gmail.com",
  "password": "PasswordRahasia",
  "name": "Arya Yunanta",
  "address": "Jl. Test"
}

### Login user
POST http://localhost:4001/api/v1/auth
Content-Type: application/json

{
  "email": "aryayun90@gmail.com",
  "password": "PasswordRahasia"
}

### List products
GET http://localhost:4001/api/v1/products

### Add cart item
POST http://localhost:4001/api/v1/cart-items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNjg1MDg4MjUyfQ.7mhZAHPAqZ5t61iwY8oAa9-Xsqo6RAoVltX03Ic21VQ

{
  "product_id": 1,
  "quantity": 2
}

### Get Cart
GET http://localhost:4001/api/v1/users/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNjg1MDg4MjUyfQ.7mhZAHPAqZ5t61iwY8oAa9-Xsqo6RAoVltX03Ic21VQ

### Delete Cart Item
DELETE http://localhost:4001/api/v1/cart-items/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNjg1MDg4MjUyfQ.7mhZAHPAqZ5t61iwY8oAa9-Xsqo6RAoVltX03Ic21VQ

### Create order
POST http://localhost:4001/api/v1/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNjg1MDg4MjUyfQ.7mhZAHPAqZ5t61iwY8oAa9-Xsqo6RAoVltX03Ic21VQ

### Pay VA
POST https://api.xendit.co/pool_virtual_accounts/simulate_payment
Content-Type: application/json
Authorization: Basic eG5kX2RldmVsb3BtZW50X3llNzhpN01hZmNWN0NGMVVQaGRGUzZtNE5qZnpYZnF0WWpsUTlLRGlKM2ZOTVpYRzNBRmRZZlN0Z3RicFo6

{
  "transfer_amount": 10000,
  "bank_account_number":"132819999318501",
  "bank_code": "BRI"
}